services:
  geocrs-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: geocrs-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  geocrs-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geocrs-ui
    ports:
      - "80:80"
    depends_on:
      - geocrs-api
    restart: unless-stopped
