services:
  geocrs-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - geocrs-ui

  geocrs-ui:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"